# Generated by Django 5.1.15 on 2026-09-02 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='Null for the person who created the organisation through onboarding. Set when Genmars added them — Charter 01 §V, nothing ships without a named owner, and access is a thing that ships.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='receives_updates',
            field=models.BooleanField(default=True, help_text="Whether this person is emailed when a progress note is published. Service mail about their own engagement, not marketing — but a second or third person at a client often does not want every note, and having no way to stop it is how service mail becomes marketing in the recipient's mind."),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Verify email'), ('reset', 'Password reset'), ('invite', 'Invitation')], max_length=16),
        ),
    ]
