# Generated by Django 5.1.15 on 2026-09-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership_invited_by_membership_receives_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('founder', 'Founder'), ('commercial', 'Commercial'), ('delivery', 'Delivery')], default='', help_text='Empty for client accounts. A staff account with no role can READ operations and change nothing — the safe state for someone whose role has not been decided yet.', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text="False revokes access without deleting the account. Django refuses to authenticate an inactive user, so this is a real revocation — and the person's authorship of notes, gates and decisions survives, which deleting them would destroy."),
        ),
    ]
