# Generated by Django 5.1.15 on 2026-09-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_staff_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Set when we stop working with them. Hides them; deletes nothing.', null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='archived_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
