# Generated by Django 5.2.17 on 2026-10-01 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organisation_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTotp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(editable=False, max_length=64)),
                ('last_step', models.BigIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff second factor',
                'verbose_name_plural': 'staff second factors',
            },
        ),
    ]
