# Generated by Django 5.1.15 on 2026-08-27 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(verbose_name='What is happening today that prompted this?')),
                ('monthly_cost', models.CharField(blank=True, max_length=200, verbose_name='Roughly what does it cost per month?')),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualifying', 'Qualifying'), ('converted', 'Converted to order'), ('declined', 'Declined')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='accounts.organisation')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('scope', models.TextField(help_text='What is being built. Charter 05 §I — fixed scope, in writing.')),
                ('exclusions', models.TextField(blank=True, help_text='What is NOT included. Charter 05 §I requires exclusions stated in writing BEFORE work begins. Showing them to the client is the point.')),
                ('status', models.CharField(choices=[('scoping', 'Scoping'), ('active', 'In progress'), ('review', 'In review'), ('delivered', 'Delivered'), ('closed', 'Closed')], default='scoping', max_length=16)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, help_text='Charter 05 §II — a change request may move this. The revised date is stated at approval, not discovered later.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_contact', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='pending', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='portal.order')),
            ],
            options={
                'ordering': ['position', 'due_on'],
            },
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('week_of', models.DateField(help_text='The Monday of the week this note covers.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='progress_notes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='portal.order')),
            ],
            options={
                'ordering': ['-week_of', '-created_at'],
                'unique_together': {('order', 'week_of')},
            },
        ),
    ]
