# Generated by Django 5.1.15 on 2026-09-01 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='converted_to',
            field=models.OneToOneField(blank=True, help_text='The order this enquiry became. Status CONVERTED without this was a dead end: it recorded that a decision happened and lost what it decided, so nobody could get from an enquiry to the work it turned into. SET_NULL rather than CASCADE — deleting an order must not erase the enquiry that produced it, which is the record of why we took the work on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_enquiry', to='portal.order'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='Charter 01 §V — nothing ships without a named owner.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiries_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='outcome_note',
            field=models.TextField(blank=True, help_text='Why this was declined, or anything the conversion needs remembered. Charter 04 §III — a decline we cannot explain six months later is a decision we did not really make.'),
        ),
    ]
