# Generated by Django 5.1.15 on 2026-09-01 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_enquiry_converted_to_enquiry_decided_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('waiting_on', models.CharField(choices=[('us', 'Us'), ('client', 'The client'), ('third_party', 'A third party')], default='us', max_length=16)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='portal.order')),
                ('raised_by', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='blockers_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cleared_at', '-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(choices=[('realistic_data', 'It works against realistic data, not the happy path only'), ('tests_in_ci', 'Automated tests cover the critical paths, and they pass in CI'), ('deployed', 'It is deployed to the target environment, not just to a branch'), ('monitored', 'Errors surface in monitoring rather than in a client phone call'), ('runbook', 'The deploy and rollback procedure is written down'), ('client_can_use', 'The client can perform the task the feature was built for, unaided')], max_length=32)),
                ('label', models.CharField(help_text='The wording at the time this gate was created. Never rewritten.', max_length=200)),
                ('met_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='How this was satisfied. A tick with no evidence is an opinion; the note is what makes it a record.')),
                ('position', models.PositiveIntegerField(default=0)),
                ('met_by', models.ForeignKey(blank=True, help_text='Charter 01 §V — nothing ships without a named owner.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gates_met', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='portal.order')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('order', 'gate')},
            },
        ),
    ]
