# Generated by Django 5.1.15 on 2026-09-02 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_blocker_deliverygate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('summary', models.CharField(help_text='One line, for the picker. What this is, not why it is good.', max_length=300)),
                ('default_scope', models.TextField(blank=True, help_text="Pre-fills an order's scope. Edited per client.")),
                ('default_exclusions', models.TextField(blank=True, help_text="Pre-fills an order's exclusions. The reason this model exists — exclusions written from scratch under time pressure come out thin.")),
                ('default_deliverables', models.TextField(blank=True, help_text='One per line. What the client actually receives.')),
                ('is_active', models.BooleanField(default=True, help_text='Retired services stay in the table. Orders and contracts reference them, and deleting one would rewrite the record of what was sold.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, help_text='What was sold. Optional: orders predate the catalogue, and some work does not fit an offering. PROTECT rather than SET_NULL — deleting a service would erase what was sold, so retire it instead.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='portal.service'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('scope', models.TextField()),
                ('exclusions', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True, help_text='One per line, as they stood when issued.')),
                ('total_kes', models.DecimalField(decimal_places=2, default=0, help_text="Summed from the order's milestones at issue. A Decimal, never a float — money through a float is money you cannot reconcile.", max_digits=12)),
                ('payment_terms', models.TextField(blank=True, help_text='Milestone names and amounts, as they stood.')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('signed', 'Signed'), ('superseded', 'Superseded'), ('void', 'Void')], default='draft', max_length=16)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('signed_on', models.DateField(blank=True, null=True)),
                ('signed_by_name', models.CharField(blank=True, help_text='The person at the client who signed.', max_length=200)),
                ('signature_note', models.TextField(blank=True, help_text='How it was signed and where the evidence is. Not a signature.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_issued', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='portal.order')),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('order', 'version')},
            },
        ),
    ]
