# Generated by Django 5.1.15 on 2026-09-02 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_service_order_service_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, help_text='GM-INV-2026-0001. Sequential, never reused — including voids.', max_length=32, unique=True)),
                ('description', models.CharField(help_text='What this bills, as it stood at issue.', max_length=300)),
                ('amount_kes', models.DecimalField(decimal_places=2, help_text='A Decimal, never a float. Money through a float is money you cannot reconcile, and this is the number on a document someone pays.', max_digits=12)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='issued', max_length=16)),
                ('issued_on', models.DateField()),
                ('due_on', models.DateField(blank=True, help_text="Stated so 'overdue' is a fact rather than a feeling.", null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='The reference from the statement — an M-Pesa code, a bank reference. What lets this row be checked against the account.', max_length=120)),
                ('void_reason', models.TextField(blank=True, help_text='Why. A voided invoice with no reason is an unanswered question.')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_issued', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='portal.milestone')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='portal.order')),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_on', '-number'],
            },
        ),
    ]
