# Generated by Django 5.1.15 on 2026-09-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='portal.service'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='tier',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
