# Generated by Django 5.1.15 on 2026-09-02 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_enquiry_service_enquiry_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Prompt sent'), ('success', 'Paid'), ('failed', 'Failed or cancelled')], default='pending', max_length=16)),
                ('result_code', models.CharField(blank=True, max_length=8)),
                ('result_desc', models.TextField(blank=True)),
                ('receipt', models.CharField(blank=True, max_length=32)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_payments', to='portal.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
