# Generated by Django 5.1.15 on 2026-09-02 16:00

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def backfill_invoice_organisation(apps, schema_editor):
    """
    Every invoice that exists today was raised against an order, and an order
    already knows its client. So the organisation is not being guessed here —
    it is being copied from the only place it could have come from.

    Anything that somehow has no order cannot be repaired automatically, and a
    wrong client on an invoice is worse than a failed migration, so this stops
    rather than inventing one.
    """
    Invoice = apps.get_model("portal", "Invoice")

    orphans = Invoice.objects.filter(order__isnull=True).values_list("number", flat=True)
    if orphans:
        raise RuntimeError(
            "These invoices have no order to take a client from: "
            + ", ".join(orphans)
            + ". Set organisation on them by hand before migrating."
        )

    for invoice in Invoice.objects.select_related("order").iterator():
        invoice.organisation_id = invoice.order.organisation_id
        invoice.save(update_fields=["organisation"])


def unbackfill(apps, schema_editor):
    """Nothing to undo: the column is dropped by the reverse of AddField."""



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_staff_roles'),
        ('portal', '0007_mpesapayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('client', 'Client'), ('staff', 'Staff')], max_length=16)),
                ('kind', models.CharField(choices=[('invoice_issued', 'Invoice issued'), ('invoice_paid', 'Invoice paid'), ('payment_recorded', 'Payment recorded'), ('invoice_voided', 'Invoice voided'), ('order_update', 'Order update'), ('enquiry_received', 'Enquiry received')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=16)),
                ('reference', models.CharField(blank=True, help_text='The M-Pesa code or bank reference, exactly as on the statement.', max_length=64)),
                ('amount_kes', models.DecimalField(decimal_places=2, help_text='How much this one payment was. Decimal, never a float.', max_digits=12)),
                ('paid_on', models.DateField()),
                ('note', models.CharField(blank=True, help_text='Anything needed to find this on a statement later.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['paid_on', 'id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='organisation',
            field=models.ForeignKey(help_text='The client this is addressed to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The project this bills, when it bills one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='portal.order'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('milestone__isnull', True), ('order__isnull', False), _connector='OR'), name='invoice_milestone_requires_order'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='portal.invoice'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='mpesa_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='record', to='portal.mpesapayment'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'audience', 'read_at'], name='notification_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('reference'), models.F('method'), condition=models.Q(('reference', ''), _negated=True), name='unique_payment_reference_per_method'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kes__gt', 0)), name='payment_amount_positive'),
        ),
            migrations.RunPython(
            backfill_invoice_organisation,
            unbackfill,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="organisation",
            field=models.ForeignKey(
                help_text="The client this is addressed to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="accounts.organisation",
            ),
        ),
    ]
