# Generated by Django 5.1.15 on 2026-09-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_backfill_payment_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('price_kes', models.DecimalField(blank=True, decimal_places=2, help_text='Null where the tier is quoted individually rather than listed.', max_digits=12, null=True)),
                ('is_from', models.BooleanField(default=False, help_text='Shown as "from KES X" — a floor, not a quote.')),
                ('lead', models.CharField(help_text='One line on who this size is for.', max_length=200)),
                ('includes', models.TextField(help_text='One item per line, in the order the website lists them.')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='portal.service')),
            ],
            options={
                'ordering': ['service', 'position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('service', 'slug'), name='unique_tier_slug_per_service')],
            },
        ),
    ]
