# Generated by Django 5.1.15 on 2026-09-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_servicetier'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_unit',
            field=models.CharField(blank=True, help_text='How the tier prices are charged: "per month", "one-time".', max_length=40),
        ),
    ]
