# Generated by Django 5.1.15 on 2026-09-02 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_staff_roles'),
        ('portal', '0011_service_price_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(help_text='What broke, in the words someone would search for.', max_length=200)),
                ('severity', models.CharField(choices=[('sev1', 'SEV-1 — system down, or data at risk'), ('sev2', 'SEV-2 — major function broken, workaround exists'), ('sev3', 'SEV-3 — minor defect, cosmetic issue')], max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('closed', 'Closed')], default='open', max_length=16)),
                ('started_at', models.DateTimeField(help_text='When it actually began — not when we noticed.')),
                ('detected_at', models.DateTimeField(help_text='When a human first knew.')),
                ('mitigated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(help_text='What was happening, plainly.')),
                ('client_impact', models.TextField(blank=True, help_text='What clients could and could not do. Blank means none — say so rather than leaving it to be assumed.')),
                ('what_happened', models.TextField(blank=True, help_text='The sequence, in order.')),
                ('why', models.TextField(blank=True, help_text='The cause. Not the trigger — the reason the trigger mattered.')),
                ('prevention', models.TextField(blank=True, help_text='What now makes this not happen again, and where that lives.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected', models.ManyToManyField(blank=True, help_text='Named clients, where the impact was specific rather than general.', related_name='incidents', to='accounts.organisation')),
                ('closed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_closed', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
