# Generated by Django 5.1.15 on 2026-09-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('invoice_issued', 'Invoice issued'), ('invoice_paid', 'Invoice paid'), ('payment_recorded', 'Payment recorded'), ('invoice_voided', 'Invoice voided'), ('order_update', 'Order update'), ('enquiry_received', 'Enquiry received'), ('incident_raised', 'Incident raised')], max_length=32),
        ),
    ]
