# Generated by Django 5.1.15 on 2026-09-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetier',
            name='published_price_kes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What genmars.co.ke publishes. Set by seed_services, never by hand.', max_digits=12, null=True),
        ),
    ]
