# Generated by Django 5.1.15 on 2026-09-02 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_staff_roles'),
        ('portal', '0015_servicetier_published_price_kes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('invoice_issued', 'Invoice issued'), ('invoice_paid', 'Invoice paid'), ('payment_recorded', 'Payment recorded'), ('invoice_voided', 'Invoice voided'), ('order_update', 'Order update'), ('enquiry_received', 'Enquiry received'), ('incident_raised', 'Incident raised'), ('offer_sent', 'Offer received'), ('task_assigned', 'Task assigned to you')], max_length=32),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('tier_name', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(help_text='What is being offered.', max_length=200)),
                ('detail', models.TextField(help_text="What it includes, in the client's language. Copied at send.")),
                ('amount_kes', models.DecimalField(decimal_places=2, help_text='Frozen when sent. Decimal, never a float.', max_digits=12)),
                ('list_price_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='draft', max_length=16)),
                ('expires_on', models.DateField(help_text='After this it is not ours to honour.')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers_accepted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers_made', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_offer', to='portal.enquiry')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='accounts.organisation')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='portal.service')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('doing', 'In progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='todo', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=8)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, help_text='Blocked on what. A blocked task with no reason is a stalled one.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(help_text='One person. Work assigned to everyone is assigned to nobody.', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Optional. Plenty of real work is not against an order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='portal.order')),
            ],
            options={
                'ordering': ['status', 'due_on', '-priority', 'id'],
                'indexes': [models.Index(fields=['assignee', 'status'], name='task_assignee_idx')],
            },
        ),
    ]
