# Generated by Django 5.1.15 on 2026-09-02 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_staff_roles'),
        ('portal', '0016_alter_notification_kind_offer_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('internal', 'Internal tool'), ('client', 'Client system'), ('product', 'Genmars product'), ('vendor', 'Third-party service')], max_length=16)),
                ('status', models.CharField(choices=[('live', 'Live'), ('building', 'Being built'), ('paused', 'Paused'), ('retired', 'Retired')], default='live', max_length=16)),
                ('criticality', models.CharField(choices=[('critical', 'Critical — an outage is a SEV-1'), ('important', 'Important — an outage is a SEV-2'), ('minor', 'Minor — an outage is a SEV-3')], max_length=16)),
                ('purpose', models.CharField(help_text='What it does, in one line.', max_length=300)),
                ('impact_if_down', models.CharField(help_text='What stops working, and for whom, if this goes down.', max_length=300)),
                ('url', models.URLField(blank=True, help_text='Where a person goes to use it.')),
                ('health_url', models.URLField(blank=True, help_text='An endpoint that answers 200 when the system is well. Must need no authentication and expose nothing.')),
                ('repository', models.CharField(blank=True, max_length=200)),
                ('runbook', models.TextField(blank=True, help_text='How to restart it, and what to check first.')),
                ('health', models.CharField(choices=[('unknown', 'Not checked'), ('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded')], default='unknown', max_length=16)),
                ('health_detail', models.CharField(blank=True, max_length=300)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, help_text='Whatever the system reports of itself.', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(blank=True, help_text='Set where we run this FOR a client. It remains theirs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systems', to='accounts.organisation')),
                ('owner', models.ForeignKey(help_text='One person. A system owned by the team is owned by nobody.', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='systems_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criticality', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Where this key lives — 'production container'.", max_length=120)),
                ('prefix', models.CharField(db_index=True, max_length=12)),
                ('hashed', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_keys_made', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='portal.system')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('message', models.CharField(max_length=300)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='portal.system')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['system', '-received_at'], name='system_event_idx')],
            },
        ),
    ]
