# Generated by Django 5.1.15 on 2026-09-02 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_staff_roles'),
        ('portal', '0017_system_systemkey_systemevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('invoice_issued', 'Invoice issued'), ('invoice_paid', 'Invoice paid'), ('payment_recorded', 'Payment recorded'), ('invoice_voided', 'Invoice voided'), ('order_update', 'Order update'), ('enquiry_received', 'Enquiry received'), ('incident_raised', 'Incident raised'), ('offer_sent', 'Offer received'), ('task_assigned', 'Task assigned to you'), ('support_reply', 'Reply on your support request'), ('support_raised', 'New support request')], max_length=32),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting', 'Waiting on the client'), ('answered', 'Answered'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_answered_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Optional. Not every question is about a project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='portal.order')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.organisation')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_label', models.CharField(blank=True, max_length=200)),
                ('from_staff', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('internal', models.BooleanField(default=False, help_text='A note between us. NEVER shown to the client — see the docstring.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.supportticket')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organisation', 'status'], name='ticket_client_idx'),
        ),
    ]
