# Generated by Django 5.1.15 on 2026-09-02 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_notification_kind_supportticket_supportmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('tier1', 'Tier 1 — before any client system goes live'), ('tier2', 'Tier 2 — within 90 days of the first paying user'), ('tier3', 'Tier 3 — before making enterprise claims')], max_length=8)),
                ('item', models.CharField(max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('not_met', 'Not met'), ('partial', 'Partly met'), ('met', 'Met'), ('n_a', 'Does not apply')], default='not_met', max_length=12)),
                ('note', models.TextField(blank=True, help_text='Evidence when met; what is missing when partial; why it does not apply when marked so.')),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_checks', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_checks', to='portal.system')),
            ],
            options={
                'ordering': ['system', 'tier', 'position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('system', 'tier', 'position'), name='one_check_per_requirement_per_system')],
            },
        ),
    ]
