# Generated by Django 5.1.15 on 2026-09-03 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_securitycheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, help_text='The registered name, as it should appear on an invoice.', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Where billing questions go. Shown on every invoice.', max_length=254)),
                ('kra_pin', models.CharField(blank=True, help_text='Required on a Kenyan tax invoice. Omitted from the document until set.', max_length=20)),
                ('postal_address', models.CharField(blank=True, max_length=300)),
                ('mpesa_paybill', models.CharField(blank=True, help_text='Paybill or till number.', max_length=20)),
                ('mpesa_account_hint', models.CharField(blank=True, help_text='What the client types in the account field. {number} becomes the invoice number.', max_length=60)),
                ('bank_details', models.TextField(blank=True, help_text='Bank, branch, account name and number, as they should be typed.')),
                ('terms', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'billing profile',
                'verbose_name_plural': 'billing profile',
            },
        ),
    ]
