# Generated by Django 5.1.15 on 2026-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_billingprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('invoice.issued', 'Invoice issued'), ('invoice.paid', 'Invoice settled'), ('payment.recorded', 'Payment recorded'), ('invoice.voided', 'Invoice voided'), ('contract.issued', 'Statement of work issued'), ('contract.signed', 'Statement of work signed'), ('contract.voided', 'Statement of work voided'), ('enquiry.converted', 'Enquiry converted to an order'), ('enquiry.declined', 'Enquiry declined'), ('price.changed', 'Tier price changed'), ('offer.sent', 'Offer sent to a client'), ('offer.accepted', 'Offer accepted'), ('offer.withdrawn', 'Offer withdrawn'), ('staff.invited', 'Staff member invited'), ('staff.role_changed', 'Staff role changed'), ('staff.deactivated', 'Staff access revoked'), ('access.granted', 'Client access granted'), ('access.revoked', 'Client access revoked'), ('task.assigned', 'Task assigned'), ('task.done', 'Task completed'), ('incident.raised', 'Incident raised'), ('incident.closed', 'Incident closed'), ('billing.changed', 'Billing details changed')], db_index=True, max_length=40),
        ),
    ]
