# Generated by Django 5.1.15 on 2026-09-04 06:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_alter_activitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('invoice.issued', 'Invoice issued'), ('invoice.paid', 'Invoice settled'), ('payment.recorded', 'Payment recorded'), ('invoice.voided', 'Invoice voided'), ('contract.issued', 'Statement of work issued'), ('contract.signed', 'Statement of work signed'), ('contract.voided', 'Statement of work voided'), ('enquiry.converted', 'Enquiry converted to an order'), ('enquiry.declined', 'Enquiry declined'), ('price.changed', 'Tier price changed'), ('offer.sent', 'Offer sent to a client'), ('offer.accepted', 'Offer accepted'), ('offer.withdrawn', 'Offer withdrawn'), ('staff.invited', 'Staff member invited'), ('staff.role_changed', 'Staff role changed'), ('staff.deactivated', 'Staff access revoked'), ('access.granted', 'Client access granted'), ('access.revoked', 'Client access revoked'), ('task.assigned', 'Task assigned'), ('task.done', 'Task completed'), ('incident.raised', 'Incident raised'), ('incident.closed', 'Incident closed'), ('billing.changed', 'Billing details changed'), ('shift.started', 'Clocked in'), ('shift.ended', 'Clocked out'), ('decision.recorded', 'Decision recorded'), ('decision.made', 'Decision made'), ('decision.superseded', 'Decision superseded'), ('decision.reversed', 'Decision reversed')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(help_text='The choice, in one line.', max_length=200)),
                ('context', models.TextField(help_text='What was true at the time that forced a choice. Required — see the docstring.')),
                ('options', models.TextField(blank=True, help_text='What else was on the table. Blank is honest when there genuinely was one option.')),
                ('decision', models.TextField(help_text='What we are doing.')),
                ('consequences', models.TextField(blank=True, help_text='What this commits us to, including what it costs.')),
                ('revisit_when', models.CharField(blank=True, help_text='What would make this worth reopening — a client size, a price, a date. The difference between a decision and a dogma.', max_length=300)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('decided', 'Decided'), ('superseded', 'Superseded'), ('reversed', 'Reversed')], db_index=True, default='proposed', max_length=16)),
                ('decided_by_label', models.CharField(blank=True, max_length=200)),
                ('decided_on', models.DateField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='portal.decision')),
            ],
            options={
                'ordering': ['-decided_on', '-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='decision_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Null means still clocked in. There is exactly one of these per person.', null=True)),
                ('started_note', models.CharField(blank=True, max_length=200)),
                ('ended_note', models.CharField(blank=True, max_length=200)),
                ('ended_late', models.BooleanField(default=False)),
                ('person', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['person', '-started_at'], name='shift_person_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('person',), name='one_open_shift_per_person'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gt', models.F('started_at')), _connector='OR'), name='shift_ends_after_it_starts')],
            },
        ),
    ]
