# Generated by Django 5.1.15 on 2026-09-04 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_staff_roles'),
        ('portal', '0022_alter_activitylog_action_decision_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('invoice.issued', 'Invoice issued'), ('invoice.paid', 'Invoice settled'), ('payment.recorded', 'Payment recorded'), ('invoice.voided', 'Invoice voided'), ('contract.issued', 'Statement of work issued'), ('contract.signed', 'Statement of work signed'), ('contract.voided', 'Statement of work voided'), ('enquiry.converted', 'Enquiry converted to an order'), ('enquiry.declined', 'Enquiry declined'), ('price.changed', 'Tier price changed'), ('offer.sent', 'Offer sent to a client'), ('offer.accepted', 'Offer accepted'), ('offer.withdrawn', 'Offer withdrawn'), ('staff.invited', 'Staff member invited'), ('staff.role_changed', 'Staff role changed'), ('staff.deactivated', 'Staff access revoked'), ('access.granted', 'Client access granted'), ('access.revoked', 'Client access revoked'), ('task.assigned', 'Task assigned'), ('task.done', 'Task completed'), ('incident.raised', 'Incident raised'), ('incident.closed', 'Incident closed'), ('billing.changed', 'Billing details changed'), ('shift.started', 'Clocked in'), ('shift.ended', 'Clocked out'), ('decision.recorded', 'Decision recorded'), ('decision.made', 'Decision made'), ('decision.superseded', 'Decision superseded'), ('decision.reversed', 'Decision reversed'), ('contact.logged', 'Conversation recorded'), ('contact.followed_up', 'Follow-up cleared'), ('client.profile_changed', 'Client details changed'), ('hosting.recorded', 'Hosting arrangement recorded'), ('hosting.changed', 'Hosting arrangement changed'), ('hosting.retired', 'Hosting arrangement retired')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_they_do', models.CharField(blank=True, help_text="One line. 'A day spa in Kilimani', not a mission statement.", max_length=200)),
                ('website', models.URLField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_role', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, help_text='As you would dial it. +254… — the country code is not optional.', max_length=40)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('preferred_channel', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('call', 'Phone call'), ('email', 'Email'), ('sms', 'SMS'), ('in_person', 'In person')], max_length=16)),
                ('client_since', models.DateField(blank=True, help_text='When we started working with them.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Standing context: how they like to work, what has gone wrong before, who else needs to be in the room. NOT a diary — a conversation goes in the contact log.')),
                ('may_be_named', models.BooleanField(default=False, help_text='Have they agreed IN WRITING that we may name them publicly?')),
                ('permission_note', models.CharField(blank=True, help_text='Where the written permission is — the file in 07-executed/, the date of the email.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Phone call'), ('email', 'Email'), ('sms', 'SMS'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=16)),
                ('direction', models.CharField(choices=[('inbound', 'They contacted us'), ('outbound', 'We contacted them')], max_length=16)),
                ('happened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('with_whom', models.CharField(blank=True, help_text='Who at the client. A name, not an account.', max_length=200)),
                ('summary', models.CharField(help_text='One line. What it was about.', max_length=300)),
                ('detail', models.TextField(blank=True, help_text='What was actually said.')),
                ('recorded_by_label', models.CharField(blank=True, max_length=200)),
                ('follow_up', models.CharField(blank=True, help_text='What WE said we would do. Blank when the answer is nothing.', max_length=300)),
                ('follow_up_by', models.DateField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups_cleared', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_log', to='portal.order')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_log', to='accounts.organisation')),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-happened_at', '-id'],
                'indexes': [models.Index(fields=['organisation', '-happened_at'], name='contact_org_idx'), models.Index(fields=['follow_up_by', 'cleared_at'], name='contact_followup_idx')],
            },
        ),
        migrations.CreateModel(
            name='HostingArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('domain', 'Domain name'), ('hosting', 'Hosting'), ('email', 'Email'), ('certificate', 'TLS certificate'), ('other', 'Other')], max_length=16)),
                ('identifier', models.CharField(help_text="The domain, the plan, the mailbox. 'clipsserenityspa.co.ke'.", max_length=200)),
                ('provider', models.CharField(blank=True, help_text='Registrar or host. Truehost, Hetzner, Zoho.', max_length=120)),
                ('account_holder', models.CharField(choices=[('client', 'The client'), ('genmars', 'Genmars')], default='client', help_text="Whose name the account is in. See this model's docstring — Charter 05 §VIII.", max_length=16)),
                ('renews_on', models.DateField(blank=True, help_text='The date it lapses if nobody acts. The reason this model exists.', null=True)),
                ('auto_renew', models.BooleanField(default=False, help_text='Whether the provider will take payment automatically. False does NOT mean it will lapse — it means a person has to act, which is exactly what gets forgotten.')),
                ('annual_cost_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annual_charge_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('retired_at', models.DateTimeField(blank=True, help_text='Set when we stop running it. Never deleted — the history is the record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting', to='accounts.organisation')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosting', to='portal.system')),
            ],
            options={
                'ordering': ['renews_on', 'identifier'],
                'indexes': [models.Index(fields=['renews_on'], name='hosting_renewal_idx')],
            },
        ),
    ]
