# Generated by Django 5.1.15 on 2026-09-04 09:07

from django.db import migrations, models


def snapshot_recipients(apps, schema_editor):
    """
    Freeze the name every offer already shows.

    Same reason as the invoice backfill: without it the field exists but is
    empty, the document falls back to the live organisation, and the first
    rename after this deploy still rewrites the "To:" line on a quote somebody
    is holding a printed copy of.
    """
    Offer = apps.get_model("portal", "Offer")
    for offer in Offer.objects.select_related("organisation").iterator():
        if not offer.offered_to_name:
            offer.offered_to_name = offer.organisation.name
            offer.save(update_fields=["offered_to_name"])


def unsnapshot(apps, schema_editor):
    """Reversing drops the column, so there is nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_invoice_billed_to_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='approach',
            field=models.TextField(blank=True, help_text='How we would do it.'),
        ),
        migrations.AddField(
            model_name='offer',
            name='context',
            field=models.TextField(blank=True, help_text='What we understood the problem to be. The client reads this first and it is where they find out we were listening — or that we were not, which is cheaper to discover here than after a deposit.'),
        ),
        migrations.AddField(
            model_name='offer',
            name='exclusions',
            field=models.TextField(blank=True, help_text='What it does not. Charter 05 §I — exclusions in writing before work begins, and a quote is before work begins.'),
        ),
        migrations.AddField(
            model_name='offer',
            name='inclusions',
            field=models.TextField(blank=True, help_text='What the price covers.'),
        ),
        migrations.AddField(
            model_name='offer',
            name='next_step',
            field=models.CharField(blank=True, help_text='What happens if they say yes. Accepting files an enquiry, which we qualify — it does not start work, and the document should not let anyone think it does.', max_length=300),
        ),
        migrations.AddField(
            model_name='offer',
            name='offered_to_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offer',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='Deposit, milestones, what is due when.'),
        ),
        migrations.AddField(
            model_name='offer',
            name='timeline',
            field=models.CharField(blank=True, help_text='An ESTIMATE of how long, in plain words. Charter 03 §IV forbids putting a commitment in front of a client that has not been tested under real conditions, so this is not a deadline and must not be worded as one.', max_length=300),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('invoice.issued', 'Invoice issued'), ('invoice.paid', 'Invoice settled'), ('payment.recorded', 'Payment recorded'), ('invoice.voided', 'Invoice voided'), ('contract.issued', 'Statement of work issued'), ('contract.signed', 'Statement of work signed'), ('contract.voided', 'Statement of work voided'), ('enquiry.converted', 'Enquiry converted to an order'), ('enquiry.declined', 'Enquiry declined'), ('price.changed', 'Tier price changed'), ('offer.sent', 'Offer sent to a client'), ('offer.accepted', 'Offer accepted'), ('offer.withdrawn', 'Offer withdrawn'), ('staff.invited', 'Staff member invited'), ('staff.role_changed', 'Staff role changed'), ('staff.deactivated', 'Staff access revoked'), ('access.granted', 'Client access granted'), ('access.revoked', 'Client access revoked'), ('task.assigned', 'Task assigned'), ('task.done', 'Task completed'), ('incident.raised', 'Incident raised'), ('incident.closed', 'Incident closed'), ('billing.changed', 'Billing details changed'), ('shift.started', 'Clocked in'), ('shift.ended', 'Clocked out'), ('decision.recorded', 'Decision recorded'), ('decision.made', 'Decision made'), ('decision.superseded', 'Decision superseded'), ('decision.reversed', 'Decision reversed'), ('contact.logged', 'Conversation recorded'), ('contact.followed_up', 'Follow-up cleared'), ('client.profile_changed', 'Client details changed'), ('client.created', 'Client added'), ('client.renamed', 'Client renamed'), ('client.archived', 'Client archived'), ('client.restored', 'Client restored'), ('client.deleted', 'Client deleted'), ('hosting.recorded', 'Hosting arrangement recorded'), ('hosting.changed', 'Hosting arrangement changed'), ('hosting.retired', 'Hosting arrangement retired')], db_index=True, max_length=40),
        ),
            migrations.RunPython(snapshot_recipients, unsnapshot),
    ]
