# Generated by Django 5.1.15 on 2026-09-04 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_offer_proposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('invoice.issued', 'Invoice issued'), ('invoice.paid', 'Invoice settled'), ('payment.recorded', 'Payment recorded'), ('invoice.voided', 'Invoice voided'), ('contract.issued', 'Statement of work issued'), ('contract.signed', 'Statement of work signed'), ('contract.voided', 'Statement of work voided'), ('enquiry.converted', 'Enquiry converted to an order'), ('enquiry.declined', 'Enquiry declined'), ('price.changed', 'Tier price changed'), ('offer.sent', 'Offer sent to a client'), ('offer.accepted', 'Offer accepted'), ('offer.withdrawn', 'Offer withdrawn'), ('staff.invited', 'Staff member invited'), ('staff.role_changed', 'Staff role changed'), ('staff.deactivated', 'Staff access revoked'), ('access.granted', 'Client access granted'), ('access.revoked', 'Client access revoked'), ('task.assigned', 'Task assigned'), ('task.done', 'Task completed'), ('incident.raised', 'Incident raised'), ('incident.closed', 'Incident closed'), ('billing.changed', 'Billing details changed'), ('shift.started', 'Clocked in'), ('shift.ended', 'Clocked out'), ('decision.recorded', 'Decision recorded'), ('decision.made', 'Decision made'), ('decision.superseded', 'Decision superseded'), ('decision.reversed', 'Decision reversed'), ('contact.logged', 'Conversation recorded'), ('contact.followed_up', 'Follow-up cleared'), ('client.profile_changed', 'Client details changed'), ('client.created', 'Client added'), ('client.renamed', 'Client renamed'), ('client.archived', 'Client archived'), ('client.restored', 'Client restored'), ('client.deleted', 'Client deleted'), ('access.requested', 'Permission requested'), ('access.approved', 'Permission granted for one act'), ('access.declined', 'Permission refused'), ('access.used', 'Granted permission used'), ('hosting.recorded', 'Hosting arrangement recorded'), ('hosting.changed', 'Hosting arrangement changed'), ('hosting.retired', 'Hosting arrangement retired')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_label', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField(help_text='Why they need it. Required — this is the entire content of the decision, and a request without one asks the founder to approve a verb.')),
                ('status', models.CharField(choices=[('pending', 'Waiting on a founder'), ('approved', 'Approved'), ('declined', 'Declined'), ('done', 'Done by a founder'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=16)),
                ('decided_by_label', models.CharField(blank=True, max_length=200)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='access_req_status_idx'), models.Index(fields=['requested_by', 'action', 'status'], name='access_req_lookup_idx')],
            },
        ),
    ]
