# Generated by Django 5.1.15 on 2026-09-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_access_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_on',
            field=models.DateField(blank=True, help_text='When the work actually finished. Set on past work recorded after the fact; a project delivered through this system gets it when its status moves to delivered.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kind',
            field=models.CharField(choices=[('project', 'Project'), ('retainer', 'Retainer'), ('updates', 'Ongoing updates'), ('hosting', 'Hosting and upkeep')], db_index=True, default='project', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='recorded_retrospectively',
            field=models.BooleanField(default=False, help_text='True for work that happened before it was entered here.'),
        ),
    ]
