# Generated by Django 5.1.15 on 2026-09-04 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organisation_archive'),
        ('portal', '0028_order_kind_and_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='decision',
            field=models.ForeignKey(blank=True, help_text='A decision that created work — the follow-through it commits us to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='portal.decision'),
        ),
        migrations.AddField(
            model_name='task',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.organisation'),
        ),
        migrations.AddField(
            model_name='task',
            name='ticket',
            field=models.ForeignKey(blank=True, help_text='The support request this is the answer to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='portal.supportticket'),
        ),
    ]
