# Generated by Django 5.1.15 on 2026-09-04 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organisation_archive'),
        ('portal', '0033_order_updated_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('invoice.issued', 'Invoice issued'), ('invoice.paid', 'Invoice settled'), ('payment.recorded', 'Payment recorded'), ('invoice.voided', 'Invoice voided'), ('contract.issued', 'Statement of work issued'), ('contract.signed', 'Statement of work signed'), ('contract.voided', 'Statement of work voided'), ('enquiry.converted', 'Enquiry converted to an order'), ('enquiry.declined', 'Enquiry declined'), ('price.changed', 'Tier price changed'), ('offer.sent', 'Offer sent to a client'), ('offer.accepted', 'Offer accepted'), ('offer.withdrawn', 'Offer withdrawn'), ('staff.invited', 'Staff member invited'), ('staff.role_changed', 'Staff role changed'), ('staff.deactivated', 'Staff access revoked'), ('access.granted', 'Client access granted'), ('access.revoked', 'Client access revoked'), ('task.assigned', 'Task assigned'), ('task.done', 'Task completed'), ('incident.raised', 'Incident raised'), ('incident.closed', 'Incident closed'), ('billing.changed', 'Billing details changed'), ('shift.started', 'Clocked in'), ('shift.ended', 'Clocked out'), ('decision.recorded', 'Decision recorded'), ('decision.made', 'Decision made'), ('decision.superseded', 'Decision superseded'), ('decision.reversed', 'Decision reversed'), ('contact.logged', 'Conversation recorded'), ('contact.followed_up', 'Follow-up cleared'), ('client.profile_changed', 'Client details changed'), ('client.created', 'Client added'), ('client.renamed', 'Client renamed'), ('client.archived', 'Client archived'), ('client.restored', 'Client restored'), ('client.deleted', 'Client deleted'), ('access.requested', 'Permission requested'), ('access.approved', 'Permission granted for one act'), ('access.declined', 'Permission refused'), ('access.used', 'Granted permission used'), ('report.exported', 'Report exported'), ('order.updated', 'Order scope or title changed'), ('hosting.recorded', 'Hosting arrangement recorded'), ('hosting.changed', 'Hosting arrangement changed'), ('hosting.retired', 'Hosting arrangement retired'), ('change.raised', 'Change request raised'), ('change.classified', 'Change request classified'), ('change.decided', 'Change request approved or declined'), ('change.closed', 'Change request closed')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('raised_by_label', models.CharField(blank=True, max_length=200)),
                ('raised_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('summary', models.CharField(help_text='What they asked for, in one line.', max_length=200)),
                ('detail', models.TextField(blank=True, help_text='Their words, as close to verbatim as possible.')),
                ('status', models.CharField(choices=[('raised', 'Awaiting classification'), ('proceeding', 'Proceeding — no commercial change'), ('awaiting', 'Awaiting your approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('done', 'Done'), ('withdrawn', 'Withdrawn')], db_index=True, default='raised', max_length=16)),
                ('classification', models.CharField(blank=True, choices=[('included', 'Included in the agreed scope'), ('clarification', 'Clarification of agreed scope'), ('defect', 'Defect — agreed scope not working'), ('change', 'Change request — new or altered requirement')], db_index=True, max_length=16)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('classification_note', models.TextField(blank=True, help_text='Why it is this and not one of the other three. Required at classification.')),
                ('cost_impact_kes', models.DecimalField(blank=True, decimal_places=2, help_text='Additional cost. 0 means priced at nothing; empty means not yet priced.', max_digits=12, null=True)),
                ('timeline_impact_days', models.IntegerField(blank=True, help_text='Days added to the target date. 0 means assessed as none.', null=True)),
                ('risk_note', models.TextField(blank=True, help_text='What this makes more likely to go wrong.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classified_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_classified', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, help_text='The logged conversation this came out of, where there was one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='portal.contactlogentry')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_decided', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='portal.order')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='accounts.organisation')),
                ('raised_by', models.ForeignKey(blank=True, help_text='Null once an account is deleted; raised_by_label survives it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-raised_at', '-id'],
                'indexes': [models.Index(fields=['organisation', 'status'], name='change_client_idx'), models.Index(fields=['order', 'status'], name='change_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('classification', ''), ('classified_at__isnull', True)), models.Q(models.Q(('classification', ''), _negated=True), ('classified_at__isnull', False)), _connector='OR'), name='change_classified_together')],
            },
        ),
    ]
