# Generated by Django 5.1.15 on 2026-09-09 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_alter_notification_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignOnApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('secret_prefix', models.CharField(blank=True, db_index=True, max_length=12)),
                ('secret_hashed', models.CharField(blank=True, max_length=255)),
                ('secret_set_at', models.DateTimeField(blank=True, null=True)),
                ('redirect_uris', models.JSONField(blank=True, default=list, help_text='Exact https addresses this app may be sent back to. Matched whole, never by prefix — a prefix match on https://app.example/ also matches https://app.example.attacker.com/.')),
                ('audience', models.CharField(choices=[('staff', 'Genmars staff only'), ('any', 'Any verified account, staff or client')], default='staff', max_length=8)),
                ('is_enabled', models.BooleanField(default=False, help_text='Off until a founder turns it on. A newly registered app with no secret and no redirect address should not be a working door.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sign_on_apps_made', to=settings.AUTH_USER_MODEL)),
                ('system', models.OneToOneField(help_text='The registered system this signs people in to. Registering it as a system first is deliberate: an application nobody owns and nobody monitors should not be issuing our identities.', on_delete=django.db.models.deletion.CASCADE, related_name='sign_on', to='portal.system')),
            ],
            options={
                'ordering': ['system__name'],
            },
        ),
        migrations.CreateModel(
            name='SignOnGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_prefix', models.CharField(db_index=True, max_length=12)),
                ('code_hashed', models.CharField(max_length=255)),
                ('redirect_uri', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='portal.signonapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_on_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['app', '-created_at'], name='signon_grant_idx')],
            },
        ),
    ]
