# Generated by Django 5.2.17 on 2026-09-12 17:03

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_alter_activitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='The address this appears at: /docs/<slug>/. Changing it after publication breaks every link anybody has saved.', max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(help_text='One sentence. It is the card on the index and the meta description in a search result, so it is a promise to somebody who has not clicked yet.', max_length=240)),
                ('category', models.CharField(choices=[('platform', 'Platform'), ('integration', 'Integrations'), ('guide', 'Guides'), ('standards', 'Engineering standards')], default='platform', max_length=16)),
                ('body', models.TextField(help_text='A restricted subset of Markdown: headings, paragraphs, lists, links, inline code and fenced code blocks. Raw HTML is not rendered — it is shown as text, on purpose.')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('building', 'In development'), ('beta', 'In beta'), ('live', 'Live')], default='building', max_length=12)),
                ('status_note', models.CharField(blank=True, default='', help_text='One line from the team on where this actually is — what works now, what is next. Published with the date it was written, so say something specific enough to be worth dating.', max_length=200)),
                ('status_changed_at', models.DateTimeField(blank=True, help_text='Stamped when the status or the note changes. Not on other edits.', null=True)),
                ('repo_url', models.URLField(blank=True, default='', help_text='Optional. A public GitHub repository this documents.', validators=[portal.models.validate_github_repo_url])),
                ('order', models.PositiveSmallIntegerField(default=100, help_text='Low numbers first, within a category.')),
                ('is_published', models.BooleanField(default=False, help_text='Included in the next website build. Not the same as live — the deploy after this is what publishes it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='First time this was marked published. Not touched by edits.', null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
                'indexes': [models.Index(fields=['is_published', 'category', 'order'], name='doc_public_idx')],
            },
        ),
    ]
