# Generated by Django 5.2.17 on 2026-09-23 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_doc_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Used in the address and as a stable key. Changing it after publication breaks every link anybody has saved.', max_length=80, unique=True)),
                ('name', models.CharField(help_text="The client, or the product's own name.", max_length=120)),
                ('category', models.CharField(choices=[('sites', 'Sites'), ('apps', 'Apps'), ('software', 'Custom software'), ('design-systems', 'Design systems'), ('tools', 'Tools'), ('integrations', 'Integrations')], default='sites', max_length=20)),
                ('label', models.CharField(choices=[('product', 'Genmars product'), ('internal', 'Internal system'), ('client', 'Client system, published with consent'), ('concept', 'Concept — designed, not deployed'), ('research', 'R&D project')], max_length=12)),
                ('sector', models.CharField(blank=True, default='', help_text='e.g. "Travel & tourism".', max_length=80)),
                ('year', models.CharField(blank=True, default='', max_length=9)),
                ('url', models.URLField(blank=True, default='', help_text='Where a reader can go and look at it, if they can.')),
                ('summary', models.CharField(help_text='One sentence. The card on the index and the meta description.', max_length=300)),
                ('detail', models.TextField(blank=True, default='', help_text='What it observably does. No invented metrics.')),
                ('capabilities', models.TextField(blank=True, default='', help_text='One per line. Short noun phrases, shown as chips.')),
                ('architecture', models.TextField(blank=True, default='')),
                ('engineering', models.TextField(blank=True, default='', help_text='Reliability, security, scalability. Usually the most persuasive part, and the part that survives the screenshots being removed.')),
                ('results', models.TextField(blank=True, default='', help_text="ONLY where real data exists. Not softened, not estimated, not replaced with 'significantly improved' — Charter 04 §IV forbids a figure that was not measured, and this is the field that invites one. Where there is no number, technical specificity in the field above convinces a reader who can evaluate it.")),
                ('permission_on_file', models.BooleanField(default=False, help_text='Written permission from the client to name them. Required before anything labelled a client system appears publicly.')),
                ('is_published', models.BooleanField(default=False, help_text='Included in the next website build. Not the same as live — the deploy after this is what publishes it.')),
                ('order', models.PositiveSmallIntegerField(default=100, help_text='Low numbers first, within a category.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'order', '-year', 'name'],
                'indexes': [models.Index(fields=['is_published', 'category', 'order'], name='work_public_idx')],
            },
        ),
    ]
