# Generated by Django 5.2.17 on 2026-09-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_activitylog_work_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('invoice_issued', 'Invoice issued'), ('invoice_paid', 'Invoice paid'), ('payment_recorded', 'Payment recorded'), ('invoice_voided', 'Invoice voided'), ('order_update', 'Order update'), ('enquiry_received', 'Enquiry received'), ('incident_raised', 'Incident raised'), ('offer_sent', 'Offer received'), ('contract_issued', 'Statement of work issued'), ('contract_signed', 'Signature recorded'), ('task_assigned', 'Task assigned to you'), ('support_reply', 'Reply on your support request'), ('support_raised', 'New support request'), ('change_raised', 'New change request'), ('change_classified', 'Change request answered'), ('change_decided', 'Change request decided')], max_length=32),
        ),
    ]
