# Generated by Django 5.2.17 on 2026-09-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_activitylog_work_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='What the picture shows, for somebody who cannot see it. Not the same as the summary — describe the image, not the project.', max_length=200),
        ),
        migrations.AddField(
            model_name='workitem',
            name='image_credit_name',
            field=models.CharField(blank=True, default='', help_text='The photographer. Required by the Unsplash licence.', max_length=120),
        ),
        migrations.AddField(
            model_name='workitem',
            name='image_credit_url',
            field=models.URLField(blank=True, default='', help_text='Their Unsplash profile, with the attribution parameters.', max_length=400),
        ),
        migrations.AddField(
            model_name='workitem',
            name='image_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='workitem',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Unsplash CDN address. Chosen in ops, never typed by hand.', max_length=500),
        ),
    ]
