# Generated by Django 5.2.17 on 2026-09-25 18:57

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_merge_20260925_1723'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('invoice.issued', 'Invoice issued'), ('invoice.paid', 'Invoice settled'), ('payment.recorded', 'Payment recorded'), ('invoice.voided', 'Invoice voided'), ('contract.issued', 'Statement of work issued'), ('contract.signed', 'Statement of work signed'), ('contract.voided', 'Statement of work voided'), ('enquiry.converted', 'Enquiry converted to an order'), ('enquiry.declined', 'Enquiry declined'), ('price.changed', 'Tier price changed'), ('offer.sent', 'Offer sent to a client'), ('offer.accepted', 'Offer accepted'), ('offer.withdrawn', 'Offer withdrawn'), ('staff.invited', 'Staff member invited'), ('staff.role_changed', 'Staff role changed'), ('staff.deactivated', 'Staff access revoked'), ('access.granted', 'Client access granted'), ('access.revoked', 'Client access revoked'), ('task.assigned', 'Task assigned'), ('task.done', 'Task completed'), ('incident.raised', 'Incident raised'), ('incident.closed', 'Incident closed'), ('billing.changed', 'Billing details changed'), ('shift.started', 'Clocked in'), ('shift.ended', 'Clocked out'), ('decision.recorded', 'Decision recorded'), ('decision.made', 'Decision made'), ('decision.superseded', 'Decision superseded'), ('decision.reversed', 'Decision reversed'), ('contact.logged', 'Conversation recorded'), ('contact.followed_up', 'Follow-up cleared'), ('client.profile_changed', 'Client details changed'), ('client.created', 'Client added'), ('client.renamed', 'Client renamed'), ('client.archived', 'Client archived'), ('client.restored', 'Client restored'), ('client.deleted', 'Client deleted'), ('access.requested', 'Permission requested'), ('access.approved', 'Permission granted for one act'), ('access.declined', 'Permission refused'), ('access.used', 'Granted permission used'), ('report.exported', 'Report exported'), ('order.updated', 'Order scope or title changed'), ('hosting.recorded', 'Hosting arrangement recorded'), ('hosting.changed', 'Hosting arrangement changed'), ('hosting.retired', 'Hosting arrangement retired'), ('change.raised', 'Change request raised'), ('change.classified', 'Change request classified'), ('change.decided', 'Change request approved or declined'), ('change.closed', 'Change request closed'), ('sign_on.configured', 'Sibling sign-on configured'), ('sign_on.secret_issued', 'Sibling sign-on secret issued'), ('sign_on.disabled', 'Sibling sign-on turned off'), ('doc.published', 'Documentation published'), ('doc.unpublished', 'Documentation withdrawn'), ('work.published', 'Work published'), ('work.withdrawn', 'Work withdrawn'), ('library.added', 'Document added to the library'), ('library.updated', 'Library document details changed'), ('library.archived', 'Library document archived'), ('library.restored', 'Library document restored'), ('library.removed', 'Library document deleted')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='LibraryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="What this is, as somebody looking for it would say it — 'Certificate of incorporation', not 'scan_003'.", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Anything the file itself does not say: what it is for, who issued it, what to do when it lapses.')),
                ('shelf', models.CharField(choices=[('policy', 'Policies and contracts'), ('compliance', 'Registration and compliance'), ('finance', 'Finance and banking'), ('supplier', 'Suppliers and services'), ('brand', 'Brand and templates'), ('other', 'Everything else')], db_index=True, default='other', max_length=16)),
                ('visibility', models.CharField(choices=[('staff', 'Any Genmars staff'), ('founder', 'Founders only')], default='staff', max_length=8)),
                ('file', models.FileField(max_length=300, upload_to=portal.models.library_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('expires_on', models.DateField(blank=True, help_text='Only if it actually lapses — a certificate or a cover note.', null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by_label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='portal.libraryfile')),
                ('uploaded_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['shelf', '-created_at'], name='portal_libr_shelf_b77ce8_idx'), models.Index(fields=['archived_at'], name='portal_libr_archive_c93fc0_idx')],
            },
        ),
    ]
