# Generated by Django 5.2.17 on 2026-09-27 21:49

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_alter_activitylog_action_mediaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='preview_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='preview_file',
            field=models.FileField(blank=True, max_length=300, upload_to=portal.models.media_preview_path),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='preview_state',
            field=models.CharField(choices=[('not_needed', 'Not needed'), ('pending', 'Being prepared'), ('ready', 'Ready'), ('failed', 'Could not be prepared')], db_index=True, default='not_needed', max_length=12),
        ),
    ]
