# Generated by Django 5.2.17 on 2026-10-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_mediaasset_preview_attempts_mediaasset_preview_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('invoice.issued', 'Invoice issued'), ('invoice.paid', 'Invoice settled'), ('payment.recorded', 'Payment recorded'), ('invoice.voided', 'Invoice voided'), ('contract.issued', 'Statement of work issued'), ('contract.signed', 'Statement of work signed'), ('contract.voided', 'Statement of work voided'), ('enquiry.converted', 'Enquiry converted to an order'), ('enquiry.declined', 'Enquiry declined'), ('price.changed', 'Tier price changed'), ('offer.sent', 'Offer sent to a client'), ('offer.accepted', 'Offer accepted'), ('offer.withdrawn', 'Offer withdrawn'), ('staff.invited', 'Staff member invited'), ('staff.role_changed', 'Staff role changed'), ('staff.deactivated', 'Staff access revoked'), ('access.granted', 'Client access granted'), ('access.revoked', 'Client access revoked'), ('task.assigned', 'Task assigned'), ('task.done', 'Task completed'), ('incident.raised', 'Incident raised'), ('incident.closed', 'Incident closed'), ('billing.changed', 'Billing details changed'), ('shift.started', 'Clocked in'), ('shift.ended', 'Clocked out'), ('decision.recorded', 'Decision recorded'), ('decision.made', 'Decision made'), ('decision.superseded', 'Decision superseded'), ('decision.reversed', 'Decision reversed'), ('contact.logged', 'Conversation recorded'), ('contact.followed_up', 'Follow-up cleared'), ('client.profile_changed', 'Client details changed'), ('client.created', 'Client added'), ('client.renamed', 'Client renamed'), ('client.archived', 'Client archived'), ('client.restored', 'Client restored'), ('client.deleted', 'Client deleted'), ('access.requested', 'Permission requested'), ('access.approved', 'Permission granted for one act'), ('access.declined', 'Permission refused'), ('access.used', 'Granted permission used'), ('report.exported', 'Report exported'), ('order.updated', 'Order scope or title changed'), ('hosting.recorded', 'Hosting arrangement recorded'), ('hosting.changed', 'Hosting arrangement changed'), ('hosting.retired', 'Hosting arrangement retired'), ('order.started', 'Work started on an order'), ('change.raised', 'Change request raised'), ('change.classified', 'Change request classified'), ('change.decided', 'Change request approved or declined'), ('change.closed', 'Change request closed'), ('sign_on.configured', 'Sibling sign-on configured'), ('sign_on.secret_issued', 'Sibling sign-on secret issued'), ('sign_on.disabled', 'Sibling sign-on turned off'), ('doc.published', 'Documentation published'), ('doc.unpublished', 'Documentation withdrawn'), ('work.published', 'Work published'), ('work.withdrawn', 'Work withdrawn'), ('library.added', 'Document added to the library'), ('library.updated', 'Library document details changed'), ('library.archived', 'Library document archived'), ('library.restored', 'Library document restored'), ('library.removed', 'Library document deleted'), ('media.added', 'Media added'), ('media.updated', 'Media details changed'), ('media.archived', 'Media archived'), ('media.restored', 'Media restored'), ('media.removed', 'Media deleted')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('invoice_issued', 'Invoice issued'), ('invoice_paid', 'Invoice paid'), ('payment_recorded', 'Payment recorded'), ('invoice_voided', 'Invoice voided'), ('order_update', 'Order update'), ('enquiry_received', 'Enquiry received'), ('incident_raised', 'Incident raised'), ('offer_sent', 'Offer received'), ('contract_issued', 'Statement of work issued'), ('contract_signed', 'Signature recorded'), ('task_assigned', 'Task assigned to you'), ('support_reply', 'Reply on your support request'), ('support_raised', 'New support request'), ('change_raised', 'New change request'), ('change_classified', 'Change request answered'), ('change_decided', 'Change request decided'), ('order_started', 'Work has started')], max_length=32),
        ),
    ]
