# Generated by Django 5.2.17 on 2026-10-02 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_mediaasset_preview_attempts_mediaasset_preview_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What we call it among ourselves. 'hetzner-shared-1'.", max_length=80, unique=True)),
                ('address', models.CharField(blank=True, help_text='How it is reached. A hostname, an IP, or the ssh alias.', max_length=200)),
                ('provider', models.CharField(blank=True, help_text='Hetzner, DigitalOcean, our own rack.', max_length=120)),
                ('location', models.CharField(blank=True, help_text='Where the machine physically is. A client asking where their data sits is asking a data-protection question, not a trivia question.', max_length=120)),
                ('vcpus', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_gb', models.PositiveIntegerField(help_text='Total disk on the machine, as the provider sells it.')),
                ('reserved_storage_gb', models.PositiveIntegerField(default=0, help_text="How much of it Genmars' own systems and headroom take. Not sellable. See this model's docstring — leaving it at zero sells our own disk to a client.")),
                ('monthly_cost_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text="A retired node keeps its arrangements, because the record of where a client's data used to sit is the thing worth keeping.")),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hostingarrangement',
            name='allocated_storage_gb',
            field=models.PositiveIntegerField(blank=True, help_text='Storage committed to this client, from their tier. What they HOLD, not what they are using — see HostingNode.', null=True),
        ),
        migrations.AddField(
            model_name='hostingarrangement',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The published tier this was sold on, where it was sold on one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosting_arrangements', to='portal.servicetier'),
        ),
        migrations.AddField(
            model_name='hostingarrangement',
            name='node',
            field=models.ForeignKey(blank=True, help_text='The Genmars machine this runs on, where it runs on one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrangements', to='portal.hostingnode'),
        ),
    ]
