"""
Two branches, each numbering its migration 0048. The second time.

WHY THIS EXISTS
───────────────
#29 added HostingNode and the capacity fields; #28 added ORDER_STARTED to
the activity log and the notification kinds. Both were cut from 0047, both
were green, and the second leaf only came into existence once both were on
main — which went red on a push nobody had touched, with 1140 errors.

0044_merge_20260925_1723 says all of this already, about #16 and #17, and
names the setting that prevents it: "require branches to be up to date
before merging", which forces the second pull request to rebase and find
the collision while it is still one person's problem. It is still not on.

WHY THIS ONE IS NOT ENOUGH ON ITS OWN, UNLIKE 0044
──────────────────────────────────────────────────
0044 was empty and that was the whole fix: neither branch touched the
other's model, so the conflict was in the graph and nowhere else.

Here BOTH branches altered the same field — ActivityLog.action — with
different sets of choices. Joining the graph picks one of them, so after
this migration alone the recorded state holds one branch's choices and
models.py holds the union of both, and `makemigrations --check` fails.

0051 carries that union. Anyone resolving the next one of these by running
`makemigrations --merge` and stopping there will ship a migration graph
that does not describe the models — run `makemigrations --check` after,
always, which is the step CI performs and the reason this was caught.
"""

# Generated by Django 5.2.17 on 2026-10-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0048_alter_activitylog_action_alter_notification_kind'),
        ('portal', '0049_alter_activitylog_action'),
    ]

    operations = [
    ]
